spring:
  application:
    name: just-met-design-pattern-service
  profiles:
    active: test


#配置日志
logging:
  #此处存放日志的路径
  path:
    config: classpath:config/logback-spring.xml
  #指定不同目录下的日志的级别
  level:
    com.shimain.springboot.mapper: DEBUG

