server:
  port: 8888
  servlet:
    context-path: /api #项目名，如果不设定，默认是 /
  tomcat:
    max-connections: 8 #设置tomcat最大连接数
    max-threads: 50 #配置最大线程数-实际处理请求的并发数

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    # REDIS (RedisProperties)
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器连接密码（默认为空）
    password:
    # 连接池最大连接数（使用负值表示没有限制）
    # 连接超时时间（毫秒）
    timeout: 0
    testOnBorrow: true
    testOnReturn: true
    jedis:
      pool:
        max-idle: 50
        max-wait: -1
        min-idle: 10
        max-active: 8

#fegin 参数设置
feign:
  hystrix:
    enabled: false
  client:
    wordprocess:
      name: "word-process"
      url: "http://127.0.0.1:12222"
