spring:
  application:
    name: just-met-mybatis-service
  profiles:
    active: local

# mybatis配置
mybatis:
  configuration:
    # 开启驼峰转换
    map-underscore-to-camel-case: true
  # 需要注意配置mapper文件的扫描路径
  mapper-locations: mybatis/**/*Mapper.xml

# db驱动配置
noah:
  driver-mysql: com.mysql.jdbc.Driver
  # driver-oracle